### ISSUE TITLE
headContentMatch regex will match <header> and not just <head

### ISSUE THREAD

**Issue by PaulKinlan** [enhance-dev/enhance-ssr-wasm#5]
The headContentMatch regex will match a string like `<header>asd <textarea></head></textarea>`

The `.*?`in `<head.*?>([\s\S]*)<\/head>` might be better as `(<head>|<head [^>]*?>)([\s\S]*)<\/head>` < I know it changes the capture groups, so maybe not exactly that.

**Comment by ryanbethel** [comment]
Thank you. You are right. I will fix that asap. The Regex is a nieve solution for breaking the parts of the document. I knew there would be edge cases, but that is a pretty big one I can easily fix. We are going to add this function to the core Enhance SSR library with a proper HTML parser. This was a way to test the API and get up and running fast. But I will fix it for now. Thanks again.

**Comment by ryanbethel** [comment]
@PaulKinlan the regex should allow for things like `<header>`. Doesn't solve textarea, but the parser based solution will be in the library soon. Again thanks for reporting it.
