### ISSUE TITLE
Install trouble ("wasm-merge failed")

### ISSUE THREAD

**Issue by eeeps** [enhance-dev/enhance-ssr-wasm#7]
<details>
<summary>Help?</summary>
<pre><code>% sh install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8831k  100 8831k    0     0  7339k      0  0:00:01  0:00:01 --:--:-- 29.5M
Password:
Installing wasm-merge...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6037k  100 6037k    0     0  5844k      0  0:00:01  0:00:01 --:--:-- 25.6M

~/dev/enhance-ssr-wasm
% l

/Users/e/dev/enhance-ssr-wasm
drwxr-xr-x    - e  4 May 00:48 .git/
drwxr-xr-x    - e  4 May 00:47 .github/
.rw-r--r--   67 e  4 May 00:47 .gitignore
drwxr-xr-x    - e 14 Sep  2023 binaryen/
.rw-r--r-- 6.2M e  4 May 00:48 binaryen-version_116-arm64-macos.tar.gz
.rw-r--r-- 1.5k e  4 May 00:47 install.sh
.rw-r--r--  11k e  4 May 00:47 LICENSE
.rw-r--r--  856 e  4 May 00:47 package.json
.rw-r--r-- 2.3k e  4 May 00:47 README.md
drwxr-xr-x    - e  4 May 00:47 scripts/
drwxr-xr-x    - e  4 May 00:47 src/
drwxr-xr-x    - e  4 May 00:47 test/

~/dev/enhance-ssr-wasm
% npm run build

> build
> rm -rf ./dist && mkdir dist && node scripts/esbuild.mjs && extism-js dist/enhance-ssr.js -i src/enhance-ssr.d.ts -o dist/enhance-ssr.wasm && rm -rf dist/enhance-ssr.js && rm -rf dist/enhance-ssr.js.map

node:internal/modules/esm/resolve:844
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from /Users/e/dev/enhance-ssr-wasm/scripts/esbuild.mjs
    at packageResolve (node:internal/modules/esm/resolve:844:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v21.6.1

?1 ~/dev/enhance-ssr-wasm
% npm i
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

added 34 packages, and audited 35 packages in 6s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

~/dev/enhance-ssr-wasm
% npm run build

> build
> rm -rf ./dist && mkdir dist && node scripts/esbuild.mjs && extism-js dist/enhance-ssr.js -i src/enhance-ssr.d.ts -o dist/enhance-ssr.wasm && rm -rf dist/enhance-ssr.js && rm -rf dist/enhance-ssr.js.map

[2024-05-04T07:50:01Z WARN  wasmtime_cache] Failed to write file with rename, lock path: /Users/e/Library/Caches/BytecodeAlliance.wasmtime/modules/wasmtime-/NYr3-kY84VvK5xhuoEKonQPfKkzxYcUTP-4RxPvQgsM.wip-atomic-write-mod, target path: /Users/e/Library/Caches/BytecodeAlliance.wasmtime/modules/wasmtime-/NYr3-kY84VvK5xhuoEKonQPfKkzxYcUTP-4RxPvQgsM, err: No such file or directory (os error 2)
warning: unknown name subsection with id 9 at 6644343
dyld[21284]: Library not loaded: @rpath/libbinaryen.dylib
  Referenced from: <DC0B3209-92D0-3500-8810-28CA50B3264F> /usr/local/binaryen/wasm-merge
  Reason: tried: '/usr/local/binaryen/../lib/libbinaryen.dylib' (no such file), '/usr/local/binaryen/../lib/libbinaryen.dylib' (no such file), '/usr/local/lib/libbinaryen.dylib' (no such file), '/usr/lib/libbinaryen.dylib' (no such file, not in dyld cache)
Error: wasm-merge failed. Couldn't merge export shim

?1 ~/dev/enhance-ssr-wasm</code></pre>

**Comment by eeeps** [comment]
So, I don't think I actually need to build this, I think I just want to snag the built file from releases. So, feel free to close.

**Comment by ryanbethel** [comment]
Cool. Glad you sorted it out. Let us know if you have any other questions or find any other problems.
